project:
  type: website
  output-dir: docs

website:
  title: "Generalized Linear Models"
  sidebar:
    background: "#9B0014"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/filippogambarota/test-quarto
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

